---
num_timesteps: 1000 #1000 timesteps with 200 episodes killed after 30 hours, also had 1mil rows in history csvs

grid_size_x: 15
grid_size_y: 35

episodes: 2

food: 100

ants: 30

species:
  - soldier
  - scout
  - runner


